/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrenajomObleceniaRouteImport } from './routes/prenajom-oblecenia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HostessFormTokenRouteImport } from './routes/hostess-form.$token'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminClothingRouteImport } from './routes/admin.clothing'
import { Route as AdminHostessesIndexRouteImport } from './routes/admin.hostesses.index'
import { Route as AdminHostessesInvitationsRouteImport } from './routes/admin.hostesses.invitations'
import { Route as AdminHostessesIdRouteImport } from './routes/admin.hostesses.$id'

const PrenajomObleceniaRoute = PrenajomObleceniaRouteImport.update({
  id: '/prenajom-oblecenia',
  path: '/prenajom-oblecenia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HostessFormTokenRoute = HostessFormTokenRouteImport.update({
  id: '/hostess-form/$token',
  path: '/hostess-form/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClothingRoute = AdminClothingRouteImport.update({
  id: '/clothing',
  path: '/clothing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostessesIndexRoute = AdminHostessesIndexRouteImport.update({
  id: '/hostesses/',
  path: '/hostesses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostessesInvitationsRoute =
  AdminHostessesInvitationsRouteImport.update({
    id: '/hostesses/invitations',
    path: '/hostesses/invitations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminHostessesIdRoute = AdminHostessesIdRouteImport.update({
  id: '/hostesses/$id',
  path: '/hostesses/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/prenajom-oblecenia': typeof PrenajomObleceniaRoute
  '/admin/clothing': typeof AdminClothingRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/hostess-form/$token': typeof HostessFormTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hostesses/$id': typeof AdminHostessesIdRoute
  '/admin/hostesses/invitations': typeof AdminHostessesInvitationsRoute
  '/admin/hostesses/': typeof AdminHostessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/prenajom-oblecenia': typeof PrenajomObleceniaRoute
  '/admin/clothing': typeof AdminClothingRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/hostess-form/$token': typeof HostessFormTokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/hostesses/$id': typeof AdminHostessesIdRoute
  '/admin/hostesses/invitations': typeof AdminHostessesInvitationsRoute
  '/admin/hostesses': typeof AdminHostessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/prenajom-oblecenia': typeof PrenajomObleceniaRoute
  '/admin/clothing': typeof AdminClothingRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/hostess-form/$token': typeof HostessFormTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hostesses/$id': typeof AdminHostessesIdRoute
  '/admin/hostesses/invitations': typeof AdminHostessesInvitationsRoute
  '/admin/hostesses/': typeof AdminHostessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/galeria'
    | '/prenajom-oblecenia'
    | '/admin/clothing'
    | '/admin/gallery'
    | '/admin/health'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/services'
    | '/admin/settings'
    | '/hostess-form/$token'
    | '/admin/'
    | '/admin/hostesses/$id'
    | '/admin/hostesses/invitations'
    | '/admin/hostesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/prenajom-oblecenia'
    | '/admin/clothing'
    | '/admin/gallery'
    | '/admin/health'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/services'
    | '/admin/settings'
    | '/hostess-form/$token'
    | '/admin'
    | '/admin/hostesses/$id'
    | '/admin/hostesses/invitations'
    | '/admin/hostesses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/galeria'
    | '/prenajom-oblecenia'
    | '/admin/clothing'
    | '/admin/gallery'
    | '/admin/health'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/services'
    | '/admin/settings'
    | '/hostess-form/$token'
    | '/admin/'
    | '/admin/hostesses/$id'
    | '/admin/hostesses/invitations'
    | '/admin/hostesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  PrenajomObleceniaRoute: typeof PrenajomObleceniaRoute
  HostessFormTokenRoute: typeof HostessFormTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prenajom-oblecenia': {
      id: '/prenajom-oblecenia'
      path: '/prenajom-oblecenia'
      fullPath: '/prenajom-oblecenia'
      preLoaderRoute: typeof PrenajomObleceniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hostess-form/$token': {
      id: '/hostess-form/$token'
      path: '/hostess-form/$token'
      fullPath: '/hostess-form/$token'
      preLoaderRoute: typeof HostessFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clothing': {
      id: '/admin/clothing'
      path: '/clothing'
      fullPath: '/admin/clothing'
      preLoaderRoute: typeof AdminClothingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hostesses/': {
      id: '/admin/hostesses/'
      path: '/hostesses'
      fullPath: '/admin/hostesses/'
      preLoaderRoute: typeof AdminHostessesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hostesses/invitations': {
      id: '/admin/hostesses/invitations'
      path: '/hostesses/invitations'
      fullPath: '/admin/hostesses/invitations'
      preLoaderRoute: typeof AdminHostessesInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hostesses/$id': {
      id: '/admin/hostesses/$id'
      path: '/hostesses/$id'
      fullPath: '/admin/hostesses/$id'
      preLoaderRoute: typeof AdminHostessesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClothingRoute: typeof AdminClothingRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminHostessesIdRoute: typeof AdminHostessesIdRoute
  AdminHostessesInvitationsRoute: typeof AdminHostessesInvitationsRoute
  AdminHostessesIndexRoute: typeof AdminHostessesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClothingRoute: AdminClothingRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminHostessesIdRoute: AdminHostessesIdRoute,
  AdminHostessesInvitationsRoute: AdminHostessesInvitationsRoute,
  AdminHostessesIndexRoute: AdminHostessesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  PrenajomObleceniaRoute: PrenajomObleceniaRoute,
  HostessFormTokenRoute: HostessFormTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
