/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrenajomObleceniaRouteImport } from './routes/prenajom-oblecenia'
import { Route as HostessFormRouteImport } from './routes/hostess-form'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminGeneratedContractsRouteImport } from './routes/admin.generated-contracts'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminClothingRouteImport } from './routes/admin.clothing'
import { Route as AdminHostessesIndexRouteImport } from './routes/admin.hostesses.index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminHostessesIdRouteImport } from './routes/admin.hostesses.$id'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminEventsIdRouteImport } from './routes/admin.events.$id'

const PrenajomObleceniaRoute = PrenajomObleceniaRouteImport.update({
  id: '/prenajom-oblecenia',
  path: '/prenajom-oblecenia',
  getParentRoute: () => rootRouteImport,
} as any)
const HostessFormRoute = HostessFormRouteImport.update({
  id: '/hostess-form',
  path: '/hostess-form',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneratedContractsRoute = AdminGeneratedContractsRouteImport.update({
  id: '/generated-contracts',
  path: '/generated-contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClothingRoute = AdminClothingRouteImport.update({
  id: '/clothing',
  path: '/clothing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostessesIndexRoute = AdminHostessesIndexRouteImport.update({
  id: '/hostesses/',
  path: '/hostesses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminHostessesIdRoute = AdminHostessesIdRouteImport.update({
  id: '/hostesses/$id',
  path: '/hostesses/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/hostess-form': typeof HostessFormRoute
  '/prenajom-oblecenia': typeof PrenajomObleceniaRoute
  '/admin/clothing': typeof AdminClothingRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/generated-contracts': typeof AdminGeneratedContractsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/hostesses/$id': typeof AdminHostessesIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/hostesses/': typeof AdminHostessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/hostess-form': typeof HostessFormRoute
  '/prenajom-oblecenia': typeof PrenajomObleceniaRoute
  '/admin/clothing': typeof AdminClothingRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/generated-contracts': typeof AdminGeneratedContractsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/hostesses/$id': typeof AdminHostessesIdRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/hostesses': typeof AdminHostessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/hostess-form': typeof HostessFormRoute
  '/prenajom-oblecenia': typeof PrenajomObleceniaRoute
  '/admin/clothing': typeof AdminClothingRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/generated-contracts': typeof AdminGeneratedContractsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/hostesses/$id': typeof AdminHostessesIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/hostesses/': typeof AdminHostessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/galeria'
    | '/hostess-form'
    | '/prenajom-oblecenia'
    | '/admin/clothing'
    | '/admin/contracts'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/generated-contracts'
    | '/admin/health'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/hostesses/$id'
    | '/admin/events/'
    | '/admin/hostesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/hostess-form'
    | '/prenajom-oblecenia'
    | '/admin/clothing'
    | '/admin/contracts'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/generated-contracts'
    | '/admin/health'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/services'
    | '/admin/settings'
    | '/admin'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/hostesses/$id'
    | '/admin/events'
    | '/admin/hostesses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/galeria'
    | '/hostess-form'
    | '/prenajom-oblecenia'
    | '/admin/clothing'
    | '/admin/contracts'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/generated-contracts'
    | '/admin/health'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/hostesses/$id'
    | '/admin/events/'
    | '/admin/hostesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  HostessFormRoute: typeof HostessFormRoute
  PrenajomObleceniaRoute: typeof PrenajomObleceniaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prenajom-oblecenia': {
      id: '/prenajom-oblecenia'
      path: '/prenajom-oblecenia'
      fullPath: '/prenajom-oblecenia'
      preLoaderRoute: typeof PrenajomObleceniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostess-form': {
      id: '/hostess-form'
      path: '/hostess-form'
      fullPath: '/hostess-form'
      preLoaderRoute: typeof HostessFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generated-contracts': {
      id: '/admin/generated-contracts'
      path: '/generated-contracts'
      fullPath: '/admin/generated-contracts'
      preLoaderRoute: typeof AdminGeneratedContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clothing': {
      id: '/admin/clothing'
      path: '/clothing'
      fullPath: '/admin/clothing'
      preLoaderRoute: typeof AdminClothingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hostesses/': {
      id: '/admin/hostesses/'
      path: '/hostesses'
      fullPath: '/admin/hostesses/'
      preLoaderRoute: typeof AdminHostessesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/hostesses/$id': {
      id: '/admin/hostesses/$id'
      path: '/hostesses/$id'
      fullPath: '/admin/hostesses/$id'
      preLoaderRoute: typeof AdminHostessesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminEventsRoute
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsIdRoute: typeof AdminEventsIdRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsIdRoute: AdminEventsIdRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminRouteChildren {
  AdminClothingRoute: typeof AdminClothingRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminGeneratedContractsRoute: typeof AdminGeneratedContractsRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminHostessesIdRoute: typeof AdminHostessesIdRoute
  AdminHostessesIndexRoute: typeof AdminHostessesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClothingRoute: AdminClothingRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminGeneratedContractsRoute: AdminGeneratedContractsRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminHostessesIdRoute: AdminHostessesIdRoute,
  AdminHostessesIndexRoute: AdminHostessesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  HostessFormRoute: HostessFormRoute,
  PrenajomObleceniaRoute: PrenajomObleceniaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
