// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpqsmowpffdnenpbjlrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwcXNtb3dwZmZkbmVucGJqbHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1MDE2NTEsImV4cCI6MjA5OTA3NzY1MX0.NzUgLzlWTWoow8We5NeRnATsSDFcPsHQi7QY4_wysQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});